frontend/src/App.jsx
frontend/src/components/auth/login/protectedRoute.jsx
frontend/src/components/auth/login/signIn.jsx

Only lets users access the webpage if they're logged in and prevents bypassing sign in through URL.

Added protected routes

---

.gitignore
frontend/.gitignore
frontend/package-lock.json
frontend/src/pages/Patients/ViewPatient.jsx

Check the View modal in the patients page to test

Add and remove prescription added

---

frontend/src/pages/Dashboard/dashboard.jsx
frontend/src/pages/Inventory/AddInventory.jsx
frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/AddPatient.jsx
frontend/src/pages/Patients/patients.jsx

some updates on ui and added the qr code for each meds

ui updates

---

frontend/package-lock.json
frontend/package.json
frontend/src/firebase/firebase.js
frontend/src/pages/Inventory/AddInventory.jsx
frontend/src/pages/Inventory/AddSupplies.jsx
frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/ViewPatient.jsx

can retrieve meds and supplies used

working branch

---

frontend/src/pages/Inventory/AddSupplies.jsx
frontend/src/pages/Inventory/inventory.jsx

wroking patient view. Can view medicine's used, supplies used.

working patient view

---

frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/AddPatient.jsx
frontend/src/pages/Patients/ViewPatient.jsx
frontend/src/pages/Patients/patients.jsx

working edit and automatic status update for supply if it is low, very low or good.

working version 3

---

frontend/src/pages/Inventory/AddInventory.jsx
frontend/src/pages/Inventory/AddSupplies.jsx
frontend/src/pages/Inventory/inventory.jsx

added cost price and retail price

added price

---

frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/AddPatient.jsx
package-lock.json
package.json

automatically updates age

---

frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/Inventory/inventory.jsx

And ang nausab ras code aside sa mga inline styles kay ang search bar ra og add buttons kay akong gi bali, niya ang edit modal sad, gi palapad nako og gipa responsive

Updated Inventory UI

---

frontend/src/pages/Billing/AddBill.jsx
frontend/src/pages/Billing/DeleteConfirmationModalBilling.jsx
frontend/src/pages/Billing/billing.jsx
frontend/src/pages/Inventory/AddInventory.jsx
frontend/src/pages/Inventory/AddSupplies.jsx
frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/AddPatient.jsx
frontend/src/pages/Patients/DeleteConfirmationModalPatient.jsx
frontend/src/pages/Patients/patients.jsx

Confirmation updates and loading when submitting updates

loading and confirmation

---

frontend/src/App.jsx
frontend/src/components/navigation/sidebar.jsx
frontend/src/components/roles/accessControl.jsx
frontend/src/context/authContext/authContext.jsx
frontend/src/pages/ErrorPages/AccessDenied.jsx
frontend/src/pages/Patients/patients.jsx

Roles with Access Patients set to false (CSR, Pharmacy) can no longer access patients page, and trying to bypass it by using URL will redirect them to an access denied page.

Added some access controls for CSR accounts

---

frontend/src/App.jsx
frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/Patients/DeleteConfirmationModalPrescription.jsx
frontend/src/pages/Patients/ViewPatient.jsx
frontend/src/pages/Patients/patients.jsx

Created a page each time you view patient.

patient updates

---

frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/Billing/billing.jsx
frontend/src/pages/Request/Transfer.jsx

added stock transfer feature. Can automatically deduct the quantity in the inventory.

stock transfer feature

---

frontend/src/components/navigation/sidebar.jsx

Temporary design for the side bar, transfer stocks feature.

stock transfer updates

---

frontend/src/pages/CSR POV/Transfer.jsx

transfer updates. CSR POV can only transfer supplies.

Transferupdates

---

frontend/src/App.jsx
frontend/src/main.jsx
frontend/src/pages/CSR POV/Transfer.jsx
frontend/src/pages/ICU POV/IcuLocalInventory.jsx
frontend/src/pages/ICU POV/requestStock.jsx

stock transfer feature where the items will not replace the first item but instead add the quantity.

Stocktransfer

---

frontend/src/pages/Patients/AddPatient.jsx

type of room now refers to the department node.

patient update

---

frontend/src/App.jsx
frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/CSR POV/Transfer.jsx
frontend/src/pages/ICU POV/ICUiewPatients.jsx
frontend/src/pages/ICU POV/requestStock.jsx
frontend/src/pages/Patients/AddPatient.jsx
frontend/src/pages/PharmacyPOV/TransferMed.jsx

Recipient Departments for the transfer stocks.

Icupatients

---

frontend/src/main.jsx
frontend/src/pages/History/CsrTransferHistory.jsx
frontend/src/pages/History/PharmacyTransferHistory.jsx

transfer history for both csr and pharmacy

Transfer history

---

backend/firebaseAdmin.js
frontend/src/pages/ICU POV/requestS.jsx
frontend/src/pages/Inventory/Notification.jsx
frontend/src/pages/Inventory/inventory.jsx
frontend/src/pages/Patients/AddPatient.jsx
frontend/src/pages/Patients/ViewPatient.jsx

minor changes to patients, if the admin is currently login can let him choose which department he will place the patient else the room type will be automatically filled based on the current user's department

Side branch

---

frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/CSR POV/CsrTransferHistory.jsx
frontend/src/pages/History/UsageHistory.jsx
frontend/src/pages/PharmacyPOV/PharmacyTransferHistory.jsx

Changes to access controls

---

frontend/src/pages/Inventory/AddInventory.jsx
frontend/src/pages/Inventory/DepartmentBreakdown.jsx
frontend/src/pages/Inventory/OverAllMedicine.jsx
frontend/src/pages/Inventory/inventory.jsx

updated inventory fields with updated edit button and overall inventory

New inventory

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/navigation/UserProfile.jsx
frontend/src/components/navigation/sidebar.jsx

Fixed overlapping issue with pages and added logout

Updated user menu in navbar

---

frontend/src/components/navigation/sidebar.jsx
frontend/src/pages/Patients/MedicineTable.jsx
frontend/src/pages/Patients/SupplyTable.jsx
frontend/src/pages/Patients/ViewPatient.jsx

Also added Billing Sections access controls

Updated view patient UI

---

frontend/src/pages/Inventory/AddInventory.jsx

updated med fields
